catch the non zero exit error

diff --git a/.github/workflows/lc-checker.yml b/.github/workflows/lc-checker.yml
--- a/.github/workflows/lc-checker.yml
+++ b/.github/workflows/lc-checker.yml
@@ -25,14 +25,22 @@ jobs:
           cache: 'pip'
           cache-dependency-path: infra/requirements-infra.txt
       
-      - name: Install check-copyright package
+      - name: Install infra dependencies
         run: |
           python -m pip install git+https://github.com/espressif/check-copyright.git@master
       
       - name: Check SPDX licenses
         id: check-licenses
         run: |
+          set +e
           output=$(python -m check_copyright --verbose --dry-run --config ./check_copyright_config.yaml .)
+          exit_code=$?
+          set -e
+          if [ $exit_code -ne 0 ]; then
+            echo "SPDX license check failed with exit code $exit_code"
+            echo "$output"
+            exit $exit_code
+          fi
           echo "::set-output name=output::$output"
           echo "$output" | grep -E "Not an Espressif|Some files are without a copyright note" > errors.txt || true
       
