just output the dry run

diff --git a/.github/workflows/lc-checker.yml b/.github/workflows/lc-checker.yml
--- a/.github/workflows/lc-checker.yml
+++ b/.github/workflows/lc-checker.yml
@@ -30,31 +30,37 @@ jobs:
       - name: Check SPDX licenses
         id: check-licenses
         run: |
-            set +e
-            output=$(python -m check_copyright --verbose --dry-run --replace --config ./check_copyright_config.yaml .)
-            exit_code=$?
-            set -e
-            echo "Output: $output"  # Add this line for debug
-            echo "::set-output name=output::$output"
-            if [ $exit_code -ne 0 ]; then
-              echo "SPDX license check failed with exit code $exit_code"
-              echo "$output"
-              exit 0  # We exit with code 0 to ensure the workflow continues
-            fi
+          output=$(python -m check_copyright --verbose --dry-run --replace --config ./check_copyright_config.yaml .)
+          if [ $? -ne 0 ]; then
+            echo "Error occurred during copyright check. See verbose output:"
+            echo "$output"
+          fi
+        
+            # set +e
+            # output=$(python -m check_copyright --verbose --dry-run --replace --config ./check_copyright_config.yaml .)
+            # exit_code=$?
+            # set -e
+            # echo "Output: $output"  # Add this line for debug
+            # echo "::set-output name=output::$output"
+            # if [ $exit_code -ne 0 ]; then
+            #   echo "SPDX license check failed with exit code $exit_code"
+            #   echo "$output"
+            #   exit 0  # We exit with code 0 to ensure the workflow continues
+            # fi
         
 
-      - name: Post comment if issues found
-        if: steps.check-licenses.outputs.output != ''
-        uses: actions/github-script@v6
-        with:
-          script: |
-            const fs = require('fs');
-            if (fs.existsSync('errors.txt')) {
-              const errors = fs.readFileSync('errors.txt', 'utf8');
-              github.rest.issues.createComment({
-                issue_number: context.issue.number,
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                body: errors
-              });
-            }
+      # - name: Post comment if issues found
+      #   if: steps.check-licenses.outputs.output != ''
+      #   uses: actions/github-script@v6
+      #   with:
+      #     script: |
+      #       const fs = require('fs');
+      #       if (fs.existsSync('errors.txt')) {
+      #         const errors = fs.readFileSync('errors.txt', 'utf8');
+      #         github.rest.issues.createComment({
+      #           issue_number: context.issue.number,
+      #           owner: context.repo.owner,
+      #           repo: context.repo.repo,
+      #           body: errors
+      #         });
+            # }
